import { useState } from 'react';
import { ST, go } from '../../core/state.js';
import { nameById } from '../../core/season.js';
import { useStore } from '../useStore.js';
import { tr, weekLabel } from '../../i18n.js';

function FixtureCard({fixture}){return <div className={'tfx'+(fixture.played?' done':'')}><div className="tfxmeta"><span>{fixture.phase==='playoffs'?(fixture.label||'PLAYOFFS'):weekLabel((fixture.week??0)+1)}</span><span>BO{fixture.bestOf||3}</span></div><div className="tfxteam"><b>{nameById(fixture.home)}</b><strong>{fixture.played?fixture.res.hMaps:'—'}</strong></div><div className="tfxteam"><b>{nameById(fixture.away)}</b><strong>{fixture.played?fixture.res.aMaps:'—'}</strong></div></div>;}
function MySchedule(){const myId=ST.teams[ST.myTeamIdx].id,fixtures=ST.schedule.flat().filter(f=>f.home===myId||f.away===myId);return <div className="tournament-fixtures">{fixtures.map(f=><FixtureCard fixture={f} key={f.id}/>)}</div>;}
function FullSchedule(){return <div className="tournament-weeks">{ST.schedule.map((week,index)=><section key={index}><h3>{week[0]?.phase==='playoffs'?(week[0]?.label||tr('플레이오프','Playoffs')):weekLabel(index+1)}</h3><div className="tournament-fixtures">{week.map(f=><FixtureCard fixture={f} key={f.id}/>)}</div></section>)}</div>;}
function Bracket(){const competition=ST.competition;if(!competition?.bracket?.length)return <div className="bracket-empty">{tr('정규시즌 종료 후 상위 8팀의 대진이 확정됩니다.','The top-eight bracket is seeded after the regular season.')}</div>;return <div className="bracket-scroll"><div className="bracket-grid">{[1,2,3,4,5,6].map(round=><section className="bracket-column" key={round}><h3>{round===6?tr('결승','Grand Final'):tr(`대진 ${round}`,`Wave ${round}`)}</h3>{competition.bracket.filter(match=>match.order===round).map(match=><div className={'bracket-match '+match.bracket} key={match.id}><div className="bracket-label">{match.label} · BO{match.bestOf}</div><div><span>{match.home==null?'TBD':nameById(match.home)}</span><b>{match.completed?match.res.hMaps:'—'}</b></div><div><span>{match.away==null?'TBD':nameById(match.away)}</span><b>{match.completed?match.res.aMaps:'—'}</b></div></div>)}</section>)}</div></div>;}
export function Tournament(){useStore();const[tab,setTab]=useState('bracket');const c=ST.competition;return <><div className="tournament-head"><div><div className="eyebrow">{tr('대회 정보','Competition')}</div><h1 className="big">{c?.name||'VCT 2026 Stage'}</h1><p>{tr('12팀 단일 리그전 후 상위 8팀 더블 엘리미네이션 · 패자조 결승과 결승 BO5','12-team full round robin, then top-eight double elimination · Lower Final and Grand Final BO5')}</p></div><button className="btn ghost" onClick={()=>go('scHub')}>{tr('허브로','Back to hub')}</button></div><div className="tournament-tabs"><button className={tab==='mine'?'on':''} onClick={()=>setTab('mine')}>{tr('우리 팀 일정','My schedule')}</button><button className={tab==='all'?'on':''} onClick={()=>setTab('all')}>{tr('전체 일정','Full schedule')}</button><button className={tab==='bracket'?'on':''} onClick={()=>setTab('bracket')}>{tr('대진표','Bracket')}</button></div>{tab==='mine'?<MySchedule/>:tab==='all'?<FullSchedule/>:<Bracket/>}</>;}
